### ISSUE TITLE
Storybook 7 compatibility

### ISSUE THREAD

**Issue by lukemcd-hero** [HipsterBrown/storybook-mirage#13]
We are working on upgrading a project to Storybook 7. The project makes heavy use of storybook-mirage (we love it!) and so want to know if plugin will be updated for compatibility with Storybook 7, especially now that SB7 is the official release.

I saw [this pull request](https://github.com/HipsterBrown/storybook-mirage/pull/12) from January and was not sure if that would be merged and if it will add compatibility.

**Comment by HipsterBrown** [comment]
@lukemcd-hero Thank you for your patience. I've been away from work for a bit since my son was born. 

I'm open to any contributions until I am back to look at the Storybook 7 compatibility. Please update this issue with any info about errors or feedback from attempting to use the canary build until then.

**Comment by lukemcd-hero** [comment]
@HipsterBrown congratulations on the birth of your son!

Testing on a fresh instance of the latest Storybook (7.0.7) on a simple React project the storybook-mirage add-on causes Storybook to completely fail as soon as you add `"storybook-mirage"` to the list of addons in config in main.js. The console shows a series of errors starting with `Warning: React.createElement: type is invalid -- expected a string (…`

I checked out the `framework-api` branch here and made the following updates:

- Change `@storybook/addon-essentials` from `^7.0.0-beta.24` to `^7.0.7`
- Change `@storybook/addon-interactions` from  `^7.0.0-beta.24` to `^7.0.7`
- Remove ` --no-manager-cache` from start script

Doing this everything is working as expected in the new Storybook interface.

**Comment by HipsterBrown** [comment]
@lukemcd-hero 

Given the few changes required to provide compatibility with Storybook 7, I've updated the branch. Can you try out `storybook-mirage@0.1.2--canary.12.3675291.0` and let me know if there are any issues? If it looks good, I'm fine with merging that update as v0.2.0 of this package.

**Comment by lukemcd-hero** [comment]
@HipsterBrown I tried out Storybook 7 with with the canary version per your instructions and everything worked flawlessly. I think you are good to upgrade the version. Thanks!

**Comment by HipsterBrown** [comment]
V0.2.0 has been shipped! Thanks for testing it 😊
