### ISSUE TITLE
handlers are not overriding the response

### ISSUE THREAD

**Issue by nimo-juice** [HipsterBrown/storybook-mirage#2]
I've setup storybook mirage, seeing it show up in the Panel, and log the API response. Changing the timing parameter in the story updates the timing for the miragejs response, so it is clearly hooked up, and some parts are working, but it seems that the handler is not overriding the API response defined in the `createMockServer` function. 

**.storybook/main.js**
```
module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/preset-create-react-app',
    'storybook-mirage',
  ],
}
```

**.storybook/preview.js**
```
export const decorators = [
  (Story) => (
    <HelmetProvider>
      <ChakraProvider theme={theme}>
        <QueryClientProvider client={queryClient}>
          <Story />
        </QueryClientProvider>
      </ChakraProvider>
    </HelmetProvider>
  ),
  StoryRouter(),
  withServer(createMockServer),
];
```

**Terms.stories.tsx**
```
export default {
  title: 'Design Language/Routes/Terms',
  component: Terms,
  parameters: {
    mirage: {
      logging: true,
      handler: {
        post: {
          'http://localhost/v1/user/signup': { termsAcceptance: false },
        },
      },
    },
  },
} as Meta;
```

**Comment by nimo-juice** [comment]
Any thoughts @HipsterBrown ? :)

**Comment by HipsterBrown** [comment]
@nimo-juice Finally got some time to explore these issues. Thank you for your patience. 

I recreated the situation locally and my best guess would be related to using `http://localhost/v1/user/signup` as the route path for the handler. Usually this is an absolute path name instead of a full URL:

```ts
export default {
  title: 'Design Language/Routes/Terms',
  component: Terms,
  parameters: {
    mirage: {
      logging: true,
      handler: {
        post: {
          '/v1/user/signup': { termsAcceptance: false },
        },
      },
    },
  },
} as Meta;
```

I know it's been a while, but I hope this helps solve the issue.

**Comment by mikolertesx** [comment]
It might help our team haha.
I{ll check it up.
