### ISSUE TITLE
Mirage add-on breaks when using interactions?

### ISSUE THREAD

**Issue by tuzmusic** [HipsterBrown/storybook-mirage#8]
I've installed the add-on, and when I initially add it to a story it works great.

However, once I start to add statements to the `play` function of the story, Mirage doesn't appear to be functioning at all.

```ts
import PlayerPropsPage from './PlayerPropsPage';
import { fireEvent, screen, waitFor } from '@storybook/testing-library';
import { expect } from '@storybook/jest';
import { Meta } from '@storybook/react';
import { playerProps } from '../../services/mocking/fixtures/playerProps.fixtures';

export default {
  component: PlayerPropsPage,
  parameters: {
    mirage: {
      logging: true,
      fixtures: {
        playerProps: playerProps.slice(0, 5),
      },
      factorySeeds: {
        playerProp: 2,
      },
    },
  },
} as Meta;

export const Default = {
  args: {},
  play: () => {
    expect(screen.getByTestId('PlayerPropsPage')).toBeInTheDocument();   // everything's fine with only this line
    expect(screen.queryAllByRole('row').length).toBeGreaterThan(1); // when I add this line, Mirage stops working.
  },
};
```

Notice that I set `logging` to true in the add-on config, so I can really confirm that with only the first assertion, mirage is getting hit, and when I add the second assertion, there is zero mirage logging.

Here are my storybook config files:

`main.js`
```js
module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    '@storybook/preset-create-react-app',
    '@storybook/addon-a11y',
    'storybook-addon-react-dev-tools',
    'storybook-addon-react-router-v6',
    'storybook-mirage'
  ],
  features: { interactionsDebugger: true },
  framework: '@storybook/react',
  core: {
    builder: '@storybook/builder-webpack5',
  },
  typescript: {
    check: false,
    checkOptions: {},
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: prop => (prop.parent ? !/node_modules/.test(prop.parent.fileName) : true),
    },
  },
};
```

`preview.js`
```js
import { AppWrapper } from '../src/AppWrapper';
import { withServer } from 'storybook-mirage/dist/withServer';
import { createMockServer } from '../src/app/services/mocking/createMockServer';

export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};

export const decorators = [
  // the test environment keeps the route handlers but ignores the seeds,
  // so that we can have total control over the seeds in our stories.
  withServer(createMockServer),
  Story => (
    <>
      <header>
        <link
          href="https://fonts.googleapis.com/css?family=Roboto:100,200,300,400,500,600,700"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,500,600,700"
          rel="stylesheet"
        />
      </header>
      <AppWrapper>{Story()}</AppWrapper>
    </>
  ),
];
```

**Comment by HipsterBrown** [comment]
@tuzmusic Can you share your `.storybook/main.js` and `.storybook/preview.js` configuration files? I had a working branch with interactions before adding the `@storybook/addon-essentials` package, so that could be related.

**Comment by tuzmusic** [comment]
> @tuzmusic Can you share your `.storybook/main.js` and `.storybook/preview.js` configuration files? I had a working branch with interactions before adding the `@storybook/addon-essentials` package, so that could be related.

Thanks, I've added them to the original post.

**Comment by HipsterBrown** [comment]
@tuzmusic Thanks for updating the description. I have a branch that I believe fixes the issue:

https://user-images.githubusercontent.com/3051193/174395230-5812e659-64fc-4463-8e1e-e119b9a69edf.mp4

Does the above screen capture appear realistic to the issue you're experiencing and the potential solution?

**Comment by tuzmusic** [comment]
@HipsterBrown it's a little bit hard to tell what I'm looking at there. But for me the Mirage tab is just blank when I add in the interactions. See my screen grab.

https://user-images.githubusercontent.com/22814728/174408439-6948cfae-fb42-4bcf-9ba4-e5c3623cdc52.mov

**Comment by HipsterBrown** [comment]
@tuzmusic I've just returned from vacation, so getting back to this issue again. Thanks for the additional code to help recreate the problem.

**Comment by fsjsd** [comment]
Hi @HipsterBrown, also experiencing this issue using interactions (mirage mocks don't complete then the interactions fail).

Is your branch published? Happy to help test
